.POSIX:

DOMAIN = svmhdvn.name
EMAIL = me@$(DOMAIN)
NAV_TITLE = \&lt;~$(USERNAME)\&gt;
CATEGORIES = posts recipes me

site: build/feed.xml package/gmi.tar.gz package/html.tar.gz

include ../../site.mk
