.POSIX:

USERNAME = svmhdvn
FULLNAME = Siva Mahadevan
DOMAIN = svmhdvn.name
EMAIL = me@$(DOMAIN)
NAV_TITLE = &lt;~$(USERNAME)&gt;
CATEGORIES = posts recipes me

blog: build/feed.xml package/gmi.tar.gz package/html.tar.gz

include ../../site.mk
