.POSIX:

include ../../Makefile

USERNAME = svmhdvn
FULLNAME = Siva Mahadevan
DOMAIN = $(DOMAIN).name
EMAIL = me@$(DOMAIN)
NAV_TITLE = &lt;~$(USERNAME)&gt;
CATEGORIES = posts recipes me

blog: build/feed.xml package/gmi.tar.gz package/html.tar.gz
