.POSIX:

DOMAIN = empt.ca
EMAIL = contact@empt.ca
NAV_TITLE = EMPT
CATEGORIES = about pricing news help FAQs

#site: build/feed.xml package/gmi.tar.gz package/html.tar.gz
site: package/gmi.tar.gz package/html.tar.gz

include ../../site.mk
