image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - shellcheck
environment:
  site: svmhdvn.srht.site
tasks:
  - lint: |
      find . -type f -name '*.sh' | xargs shellcheck -o all
  - generate: |
      make -C mysites
  - publish: |
      make -C mysites/sites/blog publish
